### PR TITLE
Added Euler Solutions and Bigints Package

### PR DESCRIPTION
**Pull request by 0xsarwagya**
### Developer Checklist
- [x] Adhered to the guidelines outlined in the README & Contributing file.
- [x] Maintained the correct directory structure (e.g., ProjectName/...yourfiles).
- [x] Please ensure to include a README file for enhanced project clarity.
- [x] Starred ⭐ the repository (optional).

### Summary
Added Solutions To Problems On Project Euler In Typescript (https://projecteuler.net/archives)

### Screenshot
N/A

### Live Project Link
N/A

### CODE REVIEW

**Comment by 0xsarwagya** [comment]
@king04aman Sir please review :)

**Comment by 0xsarwagya** [comment]
### Developer Checklist
- [x] Adhered to the guidelines outlined in the README & Contributing file.
- [x] Maintained the correct directory structure (e.g., ProjectName/...yourfiles).
- [x] Please ensure to include a README file for enhanced project clarity.
- [x] Starred ⭐ the repository (optional).

### Summary
Added Bigints Package - https://npmjs.com/package/bigints . It is a good starting point to learn building a Typescript Starter Along With Semver Release On NPM and GitHub

### Screenshot
image

### Live Project Link
https://npmjs.com/package/bigints

**Comment by 0xsarwagya** [comment]
@king04aman Sir

**Comment by 0xsarwagya** [comment]
@king04aman I have moved my projects in submodules directory sir.

**Comment by king04aman** [comment]
- LGTM

**Review by king04aman — APPROVED** [review]

**Pull request merged**
